#  VitalLink - Edge Hub Configuration


server.port=8081
spring.application.name=vitallink-edge-hub

#Kafka Producer 
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

# Topicuri Kafka
vitallink.kafka.topic.telemetry=telemetry.filtered
vitallink.kafka.topic.alerts=alerts.critical

#Scheduling
spring.task.scheduling.pool.size=5

#Virtual Threads (Java 21)
spring.threads.virtual.enabled=true

#Logging
logging.level.com.vitallink=INFO
logging.level.org.springframework.kafka=WARN
