
 # VitalLink - Production (Render) Configuration
server.port=${PORT:8080}

# PostgreSQL 
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# JPA / Hibernate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Jackson 
spring.jackson.serialization.fail-on-empty-beans=false

#  Kafka DEZACTIVAT pe productie 
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

#  Virtual Threads (Java 21) 
spring.threads.virtual.enabled=true

# JWT 
vitallink.jwt.secret=${JWT_SECRET}
vitallink.jwt.expiration-ms=86400000

# Simulator IoT dezactivat pe productie 
vitallink.simulator.enabled=false

# Logging
logging.level.com.vitallink=INFO
logging.level.org.springframework.kafka=OFF
logging.level.org.hibernate.SQL=WARN
