# ============================================================
#  VitalLink - Cloud Service Configuration
# ============================================================

server.port=8080
spring.application.name=vitallink-cloud-service

# --- PostgreSQL ------------------------------------------
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.hhfddnlxqnhngtffmqmo
spring.datasource.password=VitalLink2026db
spring.jpa.hibernate.ddl-auto=validate

# --- JPA / Hibernate -------------------------------------
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# --- Jackson ---------------------------------------------
spring.jackson.serialization.fail-on-empty-beans=false

# --- Kafka Consumer --------------------------------------
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=cloud-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# --- Topicuri Kafka --------------------------------------
vitallink.kafka.topic.telemetry=telemetry.filtered
vitallink.kafka.topic.alerts=alerts.critical

# --- Virtual Threads (Java 21) ---------------------------
spring.threads.virtual.enabled=false

# --- Redis (dezactivat momentan) -------------------------
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

# --- Logging ---------------------------------------------
logging.level.com.vitallink=INFO
logging.level.org.springframework.kafka=WARN
logging.level.org.hibernate.SQL=WARN

# --- JWT -------------------------------------------
vitallink.jwt.secret=dGhpcyBpcyBhIHZlcnkgc2VjcmV0IGtleSBmb3IgVml0YWxMaW5rIEpXVCBhdXRoZW50aWNhdGlvbiAyMDI2
vitallink.jwt.expiration-ms=86400000

